### PR TITLE
Reproducing bug

### PR DESCRIPTION
**Pull request by VincentLanglet**
```
mkdir project
cd project
git clone git@github.com:ak3l/symfony4.git
git clone git@github.com:ak3l/homestead.git
cd homestead
vagrant up
cd code
bin/console hautelook:fixtures:load
```

The site is now available on `192.168.10.10`

Go to `http://192.168.10.10/admin/app/post/37/comment/create`
Log in with `pbourdet` and `123456`.

Fill this field
image

Submit 
image

You'll get the error.

If you downgrade to Symfony-form@4.4.8, it works fine.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
This seems related to the constraint I added to the tag field.

But it works well on 4.4.8
image

**Comment by xabbuh** [comment]
@VincentLanglet Thank you for the investigations. I think you are right that this is somehow related to the `ExpressionLanguage` constraint. I am looking into it.

**Comment by VincentLanglet** [comment]
> @VincentLanglet Thank you for the investigations. I think you are right that this is somehow related to the `ExpressionLanguage` constraint. I am looking into it.

Does a project to reproduce the issue would still help you ?
I have started to create one from the symfony demo. And I don't think it will take me a lot of time.

**Comment by VincentLanglet** [comment]
https://github.com/VincentLanglet/demo/pull/1 if you need

**Comment by xabbuh** [comment]
> Does a project to reproduce the issue would still help you ?
I have started to create one from the symfony demo. And I don't think it will take me a lot of time.

I am sorry if I wasted your time on this. If you can confirm the proposed patch with your original application, your comment indeed was enough for me to find the root cause of this issue.

**Comment by VincentLanglet** [comment]
No problem, I'm happy you found the solution :)

**Pull request closed without merging**
